### ISSUE TITLE
Pages for NR lists v1 are broken

### ISSUE THREAD

**Issue by AntonPetrov** [BGSU-RNA/RNA-3D-Hub#21]
@blakesweeney 

Example:
http://rna.bgsu.edu/rna3dhub/nrlist/release/1.89

Error messages:
![screen shot 2016-09-30 at 10 19 17](https://cloud.githubusercontent.com/assets/432675/18986970/6138feba-86f7-11e6-9bbd-bb467bb0e813.png)

**Comment by blakesweeney** [comment]
This is a known issue. I'd fix it but I have to write my dissertation now. Hopefully @jjcannone can run the data migrations for the old NR set soon.

**Comment by jjcannone** [comment]
Anton -- please try again now.  (It's amazing how much better this works when I read "migrations" instead of "pipeline.")

I spot-checked ten different releases, and none showed errors.

**Comment by AntonPetrov** [comment]
Thank you very much @jjcannone! Everything is working now.
